### ISSUE TITLE
Ruby 2.0 support broken since 2.2.0: undefined method create for Tempfile:Class

### ISSUE THREAD

**Issue by zuazo** [portertech/kitchen-docker#148] opened 2015-07-27 20:35 UTC
`kitchen-docker` gem version `2.2.0` broke Ruby `2.0` support.

`Tempfile#create` does not exist in Ruby `2.0.0`, you need to use [`Tempfile.new`](http://ruby-doc.org/stdlib-2.0.0/libdoc/tempfile/rdoc/Tempfile.html#method-c-new).

This is the error (from [here](https://travis-ci.org/zuazo/kitchen-in-travis/jobs/72898919#L443)):

```
Kitchen::ActionFailed: Failed to complete #create action: [undefined method `create' for Tempfile:Class]
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/kitchen-docker-2.3.0/lib/kitchen/driver/docker.rb:252:in `build_image'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/kitchen-docker-2.3.0/lib/kitchen/driver/docker.rb:104:in `create'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `public_send'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `block in perform_action'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `call'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `synchronize_or_call'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:453:in `block in action'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:452:in `action'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `perform_action'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:352:in `create_action'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:341:in `block in transition_to'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `each'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `transition_to'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:160:in `verify'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:189:in `block in test'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:185:in `test'
/home/travis/build/zuazo/kitchen-in-travis/Rakefile:26:in `block (3 levels) in <top (required)>'
/home/travis/build/zuazo/kitchen-in-travis/Rakefile:25:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

Tasks: TOP => integration:docker
(See full trace by running task with --trace)
```

The problematic commit: 685ea608454a6883bcf8263170ceb1d3b900b8ce (issue  #136)

**Comment by coderanger** [comment] 2015-07-27 20:37
To copy from my comment over there, the fix would be:

```ruby
file = Tempfile.new('Dockerfile-kitchen', Dir.pwd)
begin
  file.write(dockerfile)
  file.close
  docker_command("#{cmd} -f #{file.path} .")
ensure
  file.close unless file.closed?
  file.unlink
end
```

But OTOH 2.1 is what comes with ChefDK so that is not an unreasonable expectation.

**Comment by metmajer** [comment] 2015-07-29 12:16
+1

**Comment by Filirom1** [comment] 2015-07-31 14:00
+1

**Comment by madhu25** [comment] 2015-08-14 13:10
+1

**Comment by matschaffer** [comment] 2015-08-25 06:30
1.9.3 also exhibits this problem

**Comment by proffalken** [comment] 2015-09-23 13:21
Hi,

Is there a fix for this yet? or should I go back to an older version of the gem?

Cheers,

Matt

**Comment by coderanger** [comment] 2015-09-23 20:02
I'll push a fix for this tomorrow, sorry for the delay.

**Comment by fabn** [comment] 2015-10-14 13:09
Any news on this?

**Comment by jdrago999** [comment] 2015-10-14 23:06
Still broken.

**Comment by jdrago999** [comment] 2015-10-14 23:32
#170 addresses this and also adds `forward_ssh_agent` option

**Comment by tanuck** [comment] 2015-10-16 11:04
@jdrago999 Why did #170 never get merged?

**Comment by bixu** [comment] 2015-10-22 14:42
I'm assuming this is still broken?  I think it's the only think keeping me from using TestKitchen at $job

**Comment by DarrellMozingo** [comment] 2015-10-27 18:56
Yea, still broken. Any word on this or why #170 was closed and not merged?

**Comment by bixu** [comment] 2015-10-28 07:05
another +1 to getting this fixed - would like to have Kitchen as an option - currently using pure rspec/serverspec as an alternative with the docker-api gem

**Comment by peco8** [comment] 2015-10-30 04:01
same here it doesn't work

**Comment by peco8** [comment] 2015-10-30 10:18
Hey I just updated the ruby version to 2.2.3 (was 2.0.0), and now different error comes out 

```
STDERR: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile-kitchen-20151030-31260-10xmvl2&memory=0&memswap=0&rm=1&t=&ulimits=null: dial unix /var/run/docker.sock: connect: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

**Comment by bixu** [comment] 2015-10-30 13:52
I think docker or docker toolbox isn't running for you...or maybe your env vars are unset

**Closed** 2015-11-02 04:45 UTC

**Comment by zuazo** [comment] 2015-11-02 13:55
Thanks @coderanger :beers:

**Comment by dj-wasabi** [comment] 2016-02-08 18:51
When will there be a new release with this fix, so I won't have to manually edit the docker.rb file? 
kitchen-docker (2.3.0) is the version that is installed with gem install kitchen-docker

**Comment by furushchev** [comment] 2016-02-19 00:30
ping

**Comment by coderanger** [comment] 2016-02-19 00:33
@furushchev Please don't poke long-since fixed issues.

**Comment by furushchev** [comment] 2016-02-19 01:20
@coderanger I think this problem is not yet solved since this fix is not applied to the version which we can get by `gem install` as @dj-wasabi says,

**Comment by dj-wasabi** [comment] 2016-02-19 06:52
@coderanger 
When I do an `gem install kitchen-docker` this issue is still there, so In my case it isn't fixed. So please create an release and make it available for `gem`.

**Comment by coderanger** [comment] 2016-02-19 06:55
I don't have permissions to create new releases, and the issue is resolved in master. I am aware there hasn't been a release in a while, I'm working on that separately.
